class Dashboard:

    def __init__(self, simulation):
        ...

    def create_window(self):
        ...

    def create_controls(self):
        ...

    def create_statistics_panel(self):
        ...

    def create_activity_panel(self):
        ...

    def update_statistics(self, metrics):
        ...

    def update_activity(self, event):
        ...

    def start_simulation(self):
        ...

    def pause_simulation(self):
        ...

    def reset_simulation(self):
        ...

    def set_simulation_speed(self, speed):
        ...

    def run(self):
        ...

    def refresh(self):
        ...