class Topology:

    def __init__(self, canvas):
        ...

    def add_sensor_node(self, sensor):
        ...

    def add_gateway_node(self, gateway):
        ...

    def add_server_node(self, server):
        ...

    def connect_nodes(self, source, destination):
        ...

    def remove_node(self, device_id):
        ...

    def update_node_status(self, device_id, status):
        ...

    def clear_topology(self):
        ...