class Gateway:

    def __init__(self, device_id, ip_address):
        ...

    def receive(self, packet):
        ...

    def validate_packet(self, packet):
        ...

    def queue_packet(self, packet):
        ...

    def process_queue(self):
        ...

    def forward_packet(self, packet):
        ...

    def get_queue_size(self):
        ...