class Transmission:

    def __init__(self, base_delay, delay_variation):
        ...

    def calculate_delay(self):
        ...

    def transmit(self, packet, source, destination):
        ...

    def get_transmission_time(self):
        ...

    def get_delivery_time(self,start_time):
        ...