class DataGenerator:

    def __init__(self):
        ...

    def generate_temperature(self):
        ...

    def generate_humidity(self):
        ...

    def generate_light(self):
        ...

    def generate_motion(self):
        ...

    def generate_soil_moisture(self):
        ...

    def generate_reading(self, sensor_type):
        ...