class Device:

    def __init__(self, device_id, ip_address, device_type):
        ...

    def activate(self):
        ...

    def deactivate(self):
        ...

    def set_ip(self, ip_address):
        ...

    def get_ip(self):
        ...

    def get_device_id(self):
        ...

    def get_status(self):
        ...

    def get_info(self):
        ...